/*
 * AWS Amplify UI Builder
 * <p>The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications. You can then connect these UI components to an application's backend Amazon Web Services resources.</p> <p>You can also use the Amplify Studio visual designer to create UI components and model data for an app. For more information, see <a href=\"https://docs.amplify.aws/console/adminui/intro\">Introduction</a> in the <i>Amplify Docs</i>.</p> <p>The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework</a>. For more information about deploying an Amplify application to Amazon Web Services, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2021-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Describes a model in a generic data schema.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:09.976251+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CodegenGenericDataModel {
  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  @javax.annotation.Nonnull
  private Map fields;

  public static final String SERIALIZED_NAME_IS_JOIN_TABLE = "isJoinTable";
  @SerializedName(SERIALIZED_NAME_IS_JOIN_TABLE)
  @javax.annotation.Nullable
  private Boolean isJoinTable;

  public static final String SERIALIZED_NAME_PRIMARY_KEYS = "primaryKeys";
  @SerializedName(SERIALIZED_NAME_PRIMARY_KEYS)
  @javax.annotation.Nonnull
  private List primaryKeys;

  public CodegenGenericDataModel() {
  }

  public CodegenGenericDataModel fields(@javax.annotation.Nonnull Map fields) {
    this.fields = fields;
    return this;
  }

  /**
   * Get fields
   * @return fields
   */
  @javax.annotation.Nonnull
  public Map getFields() {
    return fields;
  }

  public void setFields(@javax.annotation.Nonnull Map fields) {
    this.fields = fields;
  }


  public CodegenGenericDataModel isJoinTable(@javax.annotation.Nullable Boolean isJoinTable) {
    this.isJoinTable = isJoinTable;
    return this;
  }

  /**
   * Get isJoinTable
   * @return isJoinTable
   */
  @javax.annotation.Nullable
  public Boolean getIsJoinTable() {
    return isJoinTable;
  }

  public void setIsJoinTable(@javax.annotation.Nullable Boolean isJoinTable) {
    this.isJoinTable = isJoinTable;
  }


  public CodegenGenericDataModel primaryKeys(@javax.annotation.Nonnull List primaryKeys) {
    this.primaryKeys = primaryKeys;
    return this;
  }

  /**
   * Get primaryKeys
   * @return primaryKeys
   */
  @javax.annotation.Nonnull
  public List getPrimaryKeys() {
    return primaryKeys;
  }

  public void setPrimaryKeys(@javax.annotation.Nonnull List primaryKeys) {
    this.primaryKeys = primaryKeys;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodegenGenericDataModel codegenGenericDataModel = (CodegenGenericDataModel) o;
    return Objects.equals(this.fields, codegenGenericDataModel.fields) &&
        Objects.equals(this.isJoinTable, codegenGenericDataModel.isJoinTable) &&
        Objects.equals(this.primaryKeys, codegenGenericDataModel.primaryKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields, isJoinTable, primaryKeys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodegenGenericDataModel {\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    isJoinTable: ").append(toIndentedString(isJoinTable)).append("\n");
    sb.append("    primaryKeys: ").append(toIndentedString(primaryKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("fields");
    openapiFields.add("isJoinTable");
    openapiFields.add("primaryKeys");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("fields");
    openapiRequiredFields.add("primaryKeys");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CodegenGenericDataModel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CodegenGenericDataModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CodegenGenericDataModel is not found in the empty JSON string", CodegenGenericDataModel.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CodegenGenericDataModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CodegenGenericDataModel` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CodegenGenericDataModel.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `fields`
      Map.validateJsonElement(jsonObj.get("fields"));
      // validate the optional field `isJoinTable`
      if (jsonObj.get("isJoinTable") != null && !jsonObj.get("isJoinTable").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isJoinTable"));
      }
      // validate the required field `primaryKeys`
      List.validateJsonElement(jsonObj.get("primaryKeys"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CodegenGenericDataModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CodegenGenericDataModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CodegenGenericDataModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CodegenGenericDataModel.class));

       return (TypeAdapter<T>) new TypeAdapter<CodegenGenericDataModel>() {
           @Override
           public void write(JsonWriter out, CodegenGenericDataModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CodegenGenericDataModel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CodegenGenericDataModel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CodegenGenericDataModel
   * @throws IOException if the JSON string is invalid with respect to CodegenGenericDataModel
   */
  public static CodegenGenericDataModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CodegenGenericDataModel.class);
  }

  /**
   * Convert an instance of CodegenGenericDataModel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

