/*
 * AWS Amplify UI Builder
 * <p>The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications. You can then connect these UI components to an application's backend Amazon Web Services resources.</p> <p>You can also use the Amplify Studio visual designer to create UI components and model data for an app. For more information, see <a href=\"https://docs.amplify.aws/console/adminui/intro\">Introduction</a> in the <i>Amplify Docs</i>.</p> <p>The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework</a>. For more information about deploying an Amplify application to Amazon Web Services, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2021-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Describes the feature flags that you can specify for a code generation job.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:09.976251+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CodegenFeatureFlags {
  public static final String SERIALIZED_NAME_IS_RELATIONSHIP_SUPPORTED = "isRelationshipSupported";
  @SerializedName(SERIALIZED_NAME_IS_RELATIONSHIP_SUPPORTED)
  @javax.annotation.Nullable
  private Boolean isRelationshipSupported;

  public static final String SERIALIZED_NAME_IS_NON_MODEL_SUPPORTED = "isNonModelSupported";
  @SerializedName(SERIALIZED_NAME_IS_NON_MODEL_SUPPORTED)
  @javax.annotation.Nullable
  private Boolean isNonModelSupported;

  public CodegenFeatureFlags() {
  }

  public CodegenFeatureFlags isRelationshipSupported(@javax.annotation.Nullable Boolean isRelationshipSupported) {
    this.isRelationshipSupported = isRelationshipSupported;
    return this;
  }

  /**
   * Get isRelationshipSupported
   * @return isRelationshipSupported
   */
  @javax.annotation.Nullable
  public Boolean getIsRelationshipSupported() {
    return isRelationshipSupported;
  }

  public void setIsRelationshipSupported(@javax.annotation.Nullable Boolean isRelationshipSupported) {
    this.isRelationshipSupported = isRelationshipSupported;
  }


  public CodegenFeatureFlags isNonModelSupported(@javax.annotation.Nullable Boolean isNonModelSupported) {
    this.isNonModelSupported = isNonModelSupported;
    return this;
  }

  /**
   * Get isNonModelSupported
   * @return isNonModelSupported
   */
  @javax.annotation.Nullable
  public Boolean getIsNonModelSupported() {
    return isNonModelSupported;
  }

  public void setIsNonModelSupported(@javax.annotation.Nullable Boolean isNonModelSupported) {
    this.isNonModelSupported = isNonModelSupported;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodegenFeatureFlags codegenFeatureFlags = (CodegenFeatureFlags) o;
    return Objects.equals(this.isRelationshipSupported, codegenFeatureFlags.isRelationshipSupported) &&
        Objects.equals(this.isNonModelSupported, codegenFeatureFlags.isNonModelSupported);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isRelationshipSupported, isNonModelSupported);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodegenFeatureFlags {\n");
    sb.append("    isRelationshipSupported: ").append(toIndentedString(isRelationshipSupported)).append("\n");
    sb.append("    isNonModelSupported: ").append(toIndentedString(isNonModelSupported)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isRelationshipSupported");
    openapiFields.add("isNonModelSupported");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CodegenFeatureFlags
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CodegenFeatureFlags.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CodegenFeatureFlags is not found in the empty JSON string", CodegenFeatureFlags.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CodegenFeatureFlags.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CodegenFeatureFlags` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `isRelationshipSupported`
      if (jsonObj.get("isRelationshipSupported") != null && !jsonObj.get("isRelationshipSupported").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isRelationshipSupported"));
      }
      // validate the optional field `isNonModelSupported`
      if (jsonObj.get("isNonModelSupported") != null && !jsonObj.get("isNonModelSupported").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isNonModelSupported"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CodegenFeatureFlags.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CodegenFeatureFlags' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CodegenFeatureFlags> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CodegenFeatureFlags.class));

       return (TypeAdapter<T>) new TypeAdapter<CodegenFeatureFlags>() {
           @Override
           public void write(JsonWriter out, CodegenFeatureFlags value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CodegenFeatureFlags read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CodegenFeatureFlags given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CodegenFeatureFlags
   * @throws IOException if the JSON string is invalid with respect to CodegenFeatureFlags
   */
  public static CodegenFeatureFlags fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CodegenFeatureFlags.class);
  }

  /**
   * Convert an instance of CodegenFeatureFlags to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

