/*
 * AWS Amplify UI Builder
 * <p>The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications. You can then connect these UI components to an application's backend Amazon Web Services resources.</p> <p>You can also use the Amplify Studio visual designer to create UI components and model data for an app. For more information, see <a href=\"https://docs.amplify.aws/console/adminui/intro\">Introduction</a> in the <i>Amplify Docs</i>.</p> <p>The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework</a>. For more information about deploying an Amplify application to Amazon Web Services, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2021-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.JSModule;
import org.openapitools.client.model.JSScript;
import org.openapitools.client.model.JSTarget;
import org.openapitools.client.model.ReactStartCodegenJobDataApiConfiguration;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CodegenJobRenderConfigReact
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:09.976251+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CodegenJobRenderConfigReact {
  public static final String SERIALIZED_NAME_MODULE = "module";
  @SerializedName(SERIALIZED_NAME_MODULE)
  @javax.annotation.Nullable
  private JSModule module;

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  @javax.annotation.Nullable
  private JSTarget target;

  public static final String SERIALIZED_NAME_SCRIPT = "script";
  @SerializedName(SERIALIZED_NAME_SCRIPT)
  @javax.annotation.Nullable
  private JSScript script;

  public static final String SERIALIZED_NAME_RENDER_TYPE_DECLARATIONS = "renderTypeDeclarations";
  @SerializedName(SERIALIZED_NAME_RENDER_TYPE_DECLARATIONS)
  @javax.annotation.Nullable
  private Boolean renderTypeDeclarations;

  public static final String SERIALIZED_NAME_INLINE_SOURCE_MAP = "inlineSourceMap";
  @SerializedName(SERIALIZED_NAME_INLINE_SOURCE_MAP)
  @javax.annotation.Nullable
  private Boolean inlineSourceMap;

  public static final String SERIALIZED_NAME_API_CONFIGURATION = "apiConfiguration";
  @SerializedName(SERIALIZED_NAME_API_CONFIGURATION)
  @javax.annotation.Nullable
  private ReactStartCodegenJobDataApiConfiguration apiConfiguration;

  public CodegenJobRenderConfigReact() {
  }

  public CodegenJobRenderConfigReact module(@javax.annotation.Nullable JSModule module) {
    this.module = module;
    return this;
  }

  /**
   * Get module
   * @return module
   */
  @javax.annotation.Nullable
  public JSModule getModule() {
    return module;
  }

  public void setModule(@javax.annotation.Nullable JSModule module) {
    this.module = module;
  }


  public CodegenJobRenderConfigReact target(@javax.annotation.Nullable JSTarget target) {
    this.target = target;
    return this;
  }

  /**
   * Get target
   * @return target
   */
  @javax.annotation.Nullable
  public JSTarget getTarget() {
    return target;
  }

  public void setTarget(@javax.annotation.Nullable JSTarget target) {
    this.target = target;
  }


  public CodegenJobRenderConfigReact script(@javax.annotation.Nullable JSScript script) {
    this.script = script;
    return this;
  }

  /**
   * Get script
   * @return script
   */
  @javax.annotation.Nullable
  public JSScript getScript() {
    return script;
  }

  public void setScript(@javax.annotation.Nullable JSScript script) {
    this.script = script;
  }


  public CodegenJobRenderConfigReact renderTypeDeclarations(@javax.annotation.Nullable Boolean renderTypeDeclarations) {
    this.renderTypeDeclarations = renderTypeDeclarations;
    return this;
  }

  /**
   * Get renderTypeDeclarations
   * @return renderTypeDeclarations
   */
  @javax.annotation.Nullable
  public Boolean getRenderTypeDeclarations() {
    return renderTypeDeclarations;
  }

  public void setRenderTypeDeclarations(@javax.annotation.Nullable Boolean renderTypeDeclarations) {
    this.renderTypeDeclarations = renderTypeDeclarations;
  }


  public CodegenJobRenderConfigReact inlineSourceMap(@javax.annotation.Nullable Boolean inlineSourceMap) {
    this.inlineSourceMap = inlineSourceMap;
    return this;
  }

  /**
   * Get inlineSourceMap
   * @return inlineSourceMap
   */
  @javax.annotation.Nullable
  public Boolean getInlineSourceMap() {
    return inlineSourceMap;
  }

  public void setInlineSourceMap(@javax.annotation.Nullable Boolean inlineSourceMap) {
    this.inlineSourceMap = inlineSourceMap;
  }


  public CodegenJobRenderConfigReact apiConfiguration(@javax.annotation.Nullable ReactStartCodegenJobDataApiConfiguration apiConfiguration) {
    this.apiConfiguration = apiConfiguration;
    return this;
  }

  /**
   * Get apiConfiguration
   * @return apiConfiguration
   */
  @javax.annotation.Nullable
  public ReactStartCodegenJobDataApiConfiguration getApiConfiguration() {
    return apiConfiguration;
  }

  public void setApiConfiguration(@javax.annotation.Nullable ReactStartCodegenJobDataApiConfiguration apiConfiguration) {
    this.apiConfiguration = apiConfiguration;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodegenJobRenderConfigReact codegenJobRenderConfigReact = (CodegenJobRenderConfigReact) o;
    return Objects.equals(this.module, codegenJobRenderConfigReact.module) &&
        Objects.equals(this.target, codegenJobRenderConfigReact.target) &&
        Objects.equals(this.script, codegenJobRenderConfigReact.script) &&
        Objects.equals(this.renderTypeDeclarations, codegenJobRenderConfigReact.renderTypeDeclarations) &&
        Objects.equals(this.inlineSourceMap, codegenJobRenderConfigReact.inlineSourceMap) &&
        Objects.equals(this.apiConfiguration, codegenJobRenderConfigReact.apiConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(module, target, script, renderTypeDeclarations, inlineSourceMap, apiConfiguration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodegenJobRenderConfigReact {\n");
    sb.append("    module: ").append(toIndentedString(module)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    renderTypeDeclarations: ").append(toIndentedString(renderTypeDeclarations)).append("\n");
    sb.append("    inlineSourceMap: ").append(toIndentedString(inlineSourceMap)).append("\n");
    sb.append("    apiConfiguration: ").append(toIndentedString(apiConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("module");
    openapiFields.add("target");
    openapiFields.add("script");
    openapiFields.add("renderTypeDeclarations");
    openapiFields.add("inlineSourceMap");
    openapiFields.add("apiConfiguration");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CodegenJobRenderConfigReact
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CodegenJobRenderConfigReact.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CodegenJobRenderConfigReact is not found in the empty JSON string", CodegenJobRenderConfigReact.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CodegenJobRenderConfigReact.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CodegenJobRenderConfigReact` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `module`
      if (jsonObj.get("module") != null && !jsonObj.get("module").isJsonNull()) {
        JSModule.validateJsonElement(jsonObj.get("module"));
      }
      // validate the optional field `target`
      if (jsonObj.get("target") != null && !jsonObj.get("target").isJsonNull()) {
        JSTarget.validateJsonElement(jsonObj.get("target"));
      }
      // validate the optional field `script`
      if (jsonObj.get("script") != null && !jsonObj.get("script").isJsonNull()) {
        JSScript.validateJsonElement(jsonObj.get("script"));
      }
      // validate the optional field `renderTypeDeclarations`
      if (jsonObj.get("renderTypeDeclarations") != null && !jsonObj.get("renderTypeDeclarations").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("renderTypeDeclarations"));
      }
      // validate the optional field `inlineSourceMap`
      if (jsonObj.get("inlineSourceMap") != null && !jsonObj.get("inlineSourceMap").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("inlineSourceMap"));
      }
      // validate the optional field `apiConfiguration`
      if (jsonObj.get("apiConfiguration") != null && !jsonObj.get("apiConfiguration").isJsonNull()) {
        ReactStartCodegenJobDataApiConfiguration.validateJsonElement(jsonObj.get("apiConfiguration"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CodegenJobRenderConfigReact.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CodegenJobRenderConfigReact' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CodegenJobRenderConfigReact> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CodegenJobRenderConfigReact.class));

       return (TypeAdapter<T>) new TypeAdapter<CodegenJobRenderConfigReact>() {
           @Override
           public void write(JsonWriter out, CodegenJobRenderConfigReact value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CodegenJobRenderConfigReact read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CodegenJobRenderConfigReact given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CodegenJobRenderConfigReact
   * @throws IOException if the JSON string is invalid with respect to CodegenJobRenderConfigReact
   */
  public static CodegenJobRenderConfigReact fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CodegenJobRenderConfigReact.class);
  }

  /**
   * Convert an instance of CodegenJobRenderConfigReact to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

