/*
 * AWS Amplify UI Builder
 * <p>The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications. You can then connect these UI components to an application's backend Amazon Web Services resources.</p> <p>You can also use the Amplify Studio visual designer to create UI components and model data for an app. For more information, see <a href=\"https://docs.amplify.aws/console/adminui/intro\">Introduction</a> in the <i>Amplify Docs</i>.</p> <p>The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework</a>. For more information about deploying an Amplify application to Amazon Web Services, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2021-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.FormButtonsPosition;
import org.openapitools.client.model.FormCTACancel;
import org.openapitools.client.model.FormCTAClear;
import org.openapitools.client.model.FormCTASubmit;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateFormRequestFormToCreateCta
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:09.976251+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateFormRequestFormToCreateCta {
  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  @javax.annotation.Nullable
  private FormButtonsPosition position;

  public static final String SERIALIZED_NAME_CLEAR = "clear";
  @SerializedName(SERIALIZED_NAME_CLEAR)
  @javax.annotation.Nullable
  private FormCTAClear clear;

  public static final String SERIALIZED_NAME_CANCEL = "cancel";
  @SerializedName(SERIALIZED_NAME_CANCEL)
  @javax.annotation.Nullable
  private FormCTACancel cancel;

  public static final String SERIALIZED_NAME_SUBMIT = "submit";
  @SerializedName(SERIALIZED_NAME_SUBMIT)
  @javax.annotation.Nullable
  private FormCTASubmit submit;

  public CreateFormRequestFormToCreateCta() {
  }

  public CreateFormRequestFormToCreateCta position(@javax.annotation.Nullable FormButtonsPosition position) {
    this.position = position;
    return this;
  }

  /**
   * Get position
   * @return position
   */
  @javax.annotation.Nullable
  public FormButtonsPosition getPosition() {
    return position;
  }

  public void setPosition(@javax.annotation.Nullable FormButtonsPosition position) {
    this.position = position;
  }


  public CreateFormRequestFormToCreateCta clear(@javax.annotation.Nullable FormCTAClear clear) {
    this.clear = clear;
    return this;
  }

  /**
   * Get clear
   * @return clear
   */
  @javax.annotation.Nullable
  public FormCTAClear getClear() {
    return clear;
  }

  public void setClear(@javax.annotation.Nullable FormCTAClear clear) {
    this.clear = clear;
  }


  public CreateFormRequestFormToCreateCta cancel(@javax.annotation.Nullable FormCTACancel cancel) {
    this.cancel = cancel;
    return this;
  }

  /**
   * Get cancel
   * @return cancel
   */
  @javax.annotation.Nullable
  public FormCTACancel getCancel() {
    return cancel;
  }

  public void setCancel(@javax.annotation.Nullable FormCTACancel cancel) {
    this.cancel = cancel;
  }


  public CreateFormRequestFormToCreateCta submit(@javax.annotation.Nullable FormCTASubmit submit) {
    this.submit = submit;
    return this;
  }

  /**
   * Get submit
   * @return submit
   */
  @javax.annotation.Nullable
  public FormCTASubmit getSubmit() {
    return submit;
  }

  public void setSubmit(@javax.annotation.Nullable FormCTASubmit submit) {
    this.submit = submit;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateFormRequestFormToCreateCta createFormRequestFormToCreateCta = (CreateFormRequestFormToCreateCta) o;
    return Objects.equals(this.position, createFormRequestFormToCreateCta.position) &&
        Objects.equals(this.clear, createFormRequestFormToCreateCta.clear) &&
        Objects.equals(this.cancel, createFormRequestFormToCreateCta.cancel) &&
        Objects.equals(this.submit, createFormRequestFormToCreateCta.submit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(position, clear, cancel, submit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateFormRequestFormToCreateCta {\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    clear: ").append(toIndentedString(clear)).append("\n");
    sb.append("    cancel: ").append(toIndentedString(cancel)).append("\n");
    sb.append("    submit: ").append(toIndentedString(submit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("position");
    openapiFields.add("clear");
    openapiFields.add("cancel");
    openapiFields.add("submit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateFormRequestFormToCreateCta
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateFormRequestFormToCreateCta.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateFormRequestFormToCreateCta is not found in the empty JSON string", CreateFormRequestFormToCreateCta.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateFormRequestFormToCreateCta.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateFormRequestFormToCreateCta` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `position`
      if (jsonObj.get("position") != null && !jsonObj.get("position").isJsonNull()) {
        FormButtonsPosition.validateJsonElement(jsonObj.get("position"));
      }
      // validate the optional field `clear`
      if (jsonObj.get("clear") != null && !jsonObj.get("clear").isJsonNull()) {
        FormCTAClear.validateJsonElement(jsonObj.get("clear"));
      }
      // validate the optional field `cancel`
      if (jsonObj.get("cancel") != null && !jsonObj.get("cancel").isJsonNull()) {
        FormCTACancel.validateJsonElement(jsonObj.get("cancel"));
      }
      // validate the optional field `submit`
      if (jsonObj.get("submit") != null && !jsonObj.get("submit").isJsonNull()) {
        FormCTASubmit.validateJsonElement(jsonObj.get("submit"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateFormRequestFormToCreateCta.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateFormRequestFormToCreateCta' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateFormRequestFormToCreateCta> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateFormRequestFormToCreateCta.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateFormRequestFormToCreateCta>() {
           @Override
           public void write(JsonWriter out, CreateFormRequestFormToCreateCta value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateFormRequestFormToCreateCta read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateFormRequestFormToCreateCta given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateFormRequestFormToCreateCta
   * @throws IOException if the JSON string is invalid with respect to CreateFormRequestFormToCreateCta
   */
  public static CreateFormRequestFormToCreateCta fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateFormRequestFormToCreateCta.class);
  }

  /**
   * Convert an instance of CreateFormRequestFormToCreateCta to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

