/*
 * AWS Amplify UI Builder
 * <p>The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications. You can then connect these UI components to an application's backend Amazon Web Services resources.</p> <p>You can also use the Amplify Studio visual designer to create UI components and model data for an app. For more information, see <a href=\"https://docs.amplify.aws/console/adminui/intro\">Introduction</a> in the <i>Amplify Docs</i>.</p> <p>The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework</a>. For more information about deploying an Amplify application to Amazon Web Services, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2021-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.FormStyleHorizontalGap;
import org.openapitools.client.model.FormStyleOuterPadding;
import org.openapitools.client.model.FormStyleVerticalGap;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * FormStyle
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:09.976251+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class FormStyle {
  public static final String SERIALIZED_NAME_HORIZONTAL_GAP = "horizontalGap";
  @SerializedName(SERIALIZED_NAME_HORIZONTAL_GAP)
  @javax.annotation.Nullable
  private FormStyleHorizontalGap horizontalGap;

  public static final String SERIALIZED_NAME_VERTICAL_GAP = "verticalGap";
  @SerializedName(SERIALIZED_NAME_VERTICAL_GAP)
  @javax.annotation.Nullable
  private FormStyleVerticalGap verticalGap;

  public static final String SERIALIZED_NAME_OUTER_PADDING = "outerPadding";
  @SerializedName(SERIALIZED_NAME_OUTER_PADDING)
  @javax.annotation.Nullable
  private FormStyleOuterPadding outerPadding;

  public FormStyle() {
  }

  public FormStyle horizontalGap(@javax.annotation.Nullable FormStyleHorizontalGap horizontalGap) {
    this.horizontalGap = horizontalGap;
    return this;
  }

  /**
   * Get horizontalGap
   * @return horizontalGap
   */
  @javax.annotation.Nullable
  public FormStyleHorizontalGap getHorizontalGap() {
    return horizontalGap;
  }

  public void setHorizontalGap(@javax.annotation.Nullable FormStyleHorizontalGap horizontalGap) {
    this.horizontalGap = horizontalGap;
  }


  public FormStyle verticalGap(@javax.annotation.Nullable FormStyleVerticalGap verticalGap) {
    this.verticalGap = verticalGap;
    return this;
  }

  /**
   * Get verticalGap
   * @return verticalGap
   */
  @javax.annotation.Nullable
  public FormStyleVerticalGap getVerticalGap() {
    return verticalGap;
  }

  public void setVerticalGap(@javax.annotation.Nullable FormStyleVerticalGap verticalGap) {
    this.verticalGap = verticalGap;
  }


  public FormStyle outerPadding(@javax.annotation.Nullable FormStyleOuterPadding outerPadding) {
    this.outerPadding = outerPadding;
    return this;
  }

  /**
   * Get outerPadding
   * @return outerPadding
   */
  @javax.annotation.Nullable
  public FormStyleOuterPadding getOuterPadding() {
    return outerPadding;
  }

  public void setOuterPadding(@javax.annotation.Nullable FormStyleOuterPadding outerPadding) {
    this.outerPadding = outerPadding;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormStyle formStyle = (FormStyle) o;
    return Objects.equals(this.horizontalGap, formStyle.horizontalGap) &&
        Objects.equals(this.verticalGap, formStyle.verticalGap) &&
        Objects.equals(this.outerPadding, formStyle.outerPadding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(horizontalGap, verticalGap, outerPadding);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormStyle {\n");
    sb.append("    horizontalGap: ").append(toIndentedString(horizontalGap)).append("\n");
    sb.append("    verticalGap: ").append(toIndentedString(verticalGap)).append("\n");
    sb.append("    outerPadding: ").append(toIndentedString(outerPadding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("horizontalGap");
    openapiFields.add("verticalGap");
    openapiFields.add("outerPadding");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FormStyle
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FormStyle.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FormStyle is not found in the empty JSON string", FormStyle.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FormStyle.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FormStyle` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `horizontalGap`
      if (jsonObj.get("horizontalGap") != null && !jsonObj.get("horizontalGap").isJsonNull()) {
        FormStyleHorizontalGap.validateJsonElement(jsonObj.get("horizontalGap"));
      }
      // validate the optional field `verticalGap`
      if (jsonObj.get("verticalGap") != null && !jsonObj.get("verticalGap").isJsonNull()) {
        FormStyleVerticalGap.validateJsonElement(jsonObj.get("verticalGap"));
      }
      // validate the optional field `outerPadding`
      if (jsonObj.get("outerPadding") != null && !jsonObj.get("outerPadding").isJsonNull()) {
        FormStyleOuterPadding.validateJsonElement(jsonObj.get("outerPadding"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FormStyle.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FormStyle' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FormStyle> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FormStyle.class));

       return (TypeAdapter<T>) new TypeAdapter<FormStyle>() {
           @Override
           public void write(JsonWriter out, FormStyle value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FormStyle read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FormStyle given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FormStyle
   * @throws IOException if the JSON string is invalid with respect to FormStyle
   */
  public static FormStyle fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FormStyle.class);
  }

  /**
   * Convert an instance of FormStyle to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

