/*
 * AWS Amplify UI Builder
 * <p>The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications. You can then connect these UI components to an application's backend Amazon Web Services resources.</p> <p>You can also use the Amplify Studio visual designer to create UI components and model data for an app. For more information, see <a href=\"https://docs.amplify.aws/console/adminui/intro\">Introduction</a> in the <i>Amplify Docs</i>.</p> <p>The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework</a>. For more information about deploying an Amplify application to Amazon Web Services, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2021-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Stores information for generating Amplify DataStore queries. Use a &lt;code&gt;Predicate&lt;/code&gt; to retrieve a subset of the data in a collection.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:09.976251+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class Predicate {
  public static final String SERIALIZED_NAME_OR = "or";
  @SerializedName(SERIALIZED_NAME_OR)
  @javax.annotation.Nullable
  private List or;

  public static final String SERIALIZED_NAME_AND = "and";
  @SerializedName(SERIALIZED_NAME_AND)
  @javax.annotation.Nullable
  private List and;

  public static final String SERIALIZED_NAME_FIELD = "field";
  @SerializedName(SERIALIZED_NAME_FIELD)
  @javax.annotation.Nullable
  private String field;

  public static final String SERIALIZED_NAME_OPERATOR = "operator";
  @SerializedName(SERIALIZED_NAME_OPERATOR)
  @javax.annotation.Nullable
  private String operator;

  public static final String SERIALIZED_NAME_OPERAND = "operand";
  @SerializedName(SERIALIZED_NAME_OPERAND)
  @javax.annotation.Nullable
  private String operand;

  public static final String SERIALIZED_NAME_OPERAND_TYPE = "operandType";
  @SerializedName(SERIALIZED_NAME_OPERAND_TYPE)
  @javax.annotation.Nullable
  private String operandType;

  public Predicate() {
  }

  public Predicate or(@javax.annotation.Nullable List or) {
    this.or = or;
    return this;
  }

  /**
   * Get or
   * @return or
   */
  @javax.annotation.Nullable
  public List getOr() {
    return or;
  }

  public void setOr(@javax.annotation.Nullable List or) {
    this.or = or;
  }


  public Predicate and(@javax.annotation.Nullable List and) {
    this.and = and;
    return this;
  }

  /**
   * Get and
   * @return and
   */
  @javax.annotation.Nullable
  public List getAnd() {
    return and;
  }

  public void setAnd(@javax.annotation.Nullable List and) {
    this.and = and;
  }


  public Predicate field(@javax.annotation.Nullable String field) {
    this.field = field;
    return this;
  }

  /**
   * Get field
   * @return field
   */
  @javax.annotation.Nullable
  public String getField() {
    return field;
  }

  public void setField(@javax.annotation.Nullable String field) {
    this.field = field;
  }


  public Predicate operator(@javax.annotation.Nullable String operator) {
    this.operator = operator;
    return this;
  }

  /**
   * Get operator
   * @return operator
   */
  @javax.annotation.Nullable
  public String getOperator() {
    return operator;
  }

  public void setOperator(@javax.annotation.Nullable String operator) {
    this.operator = operator;
  }


  public Predicate operand(@javax.annotation.Nullable String operand) {
    this.operand = operand;
    return this;
  }

  /**
   * Get operand
   * @return operand
   */
  @javax.annotation.Nullable
  public String getOperand() {
    return operand;
  }

  public void setOperand(@javax.annotation.Nullable String operand) {
    this.operand = operand;
  }


  public Predicate operandType(@javax.annotation.Nullable String operandType) {
    this.operandType = operandType;
    return this;
  }

  /**
   * Get operandType
   * @return operandType
   */
  @javax.annotation.Nullable
  public String getOperandType() {
    return operandType;
  }

  public void setOperandType(@javax.annotation.Nullable String operandType) {
    this.operandType = operandType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Predicate predicate = (Predicate) o;
    return Objects.equals(this.or, predicate.or) &&
        Objects.equals(this.and, predicate.and) &&
        Objects.equals(this.field, predicate.field) &&
        Objects.equals(this.operator, predicate.operator) &&
        Objects.equals(this.operand, predicate.operand) &&
        Objects.equals(this.operandType, predicate.operandType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(or, and, field, operator, operand, operandType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Predicate {\n");
    sb.append("    or: ").append(toIndentedString(or)).append("\n");
    sb.append("    and: ").append(toIndentedString(and)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    operand: ").append(toIndentedString(operand)).append("\n");
    sb.append("    operandType: ").append(toIndentedString(operandType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("or");
    openapiFields.add("and");
    openapiFields.add("field");
    openapiFields.add("operator");
    openapiFields.add("operand");
    openapiFields.add("operandType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Predicate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Predicate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Predicate is not found in the empty JSON string", Predicate.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Predicate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Predicate` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `or`
      if (jsonObj.get("or") != null && !jsonObj.get("or").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("or"));
      }
      // validate the optional field `and`
      if (jsonObj.get("and") != null && !jsonObj.get("and").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("and"));
      }
      // validate the optional field `field`
      if (jsonObj.get("field") != null && !jsonObj.get("field").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("field"));
      }
      // validate the optional field `operator`
      if (jsonObj.get("operator") != null && !jsonObj.get("operator").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("operator"));
      }
      // validate the optional field `operand`
      if (jsonObj.get("operand") != null && !jsonObj.get("operand").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("operand"));
      }
      // validate the optional field `operandType`
      if (jsonObj.get("operandType") != null && !jsonObj.get("operandType").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("operandType"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Predicate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Predicate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Predicate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Predicate.class));

       return (TypeAdapter<T>) new TypeAdapter<Predicate>() {
           @Override
           public void write(JsonWriter out, Predicate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Predicate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Predicate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Predicate
   * @throws IOException if the JSON string is invalid with respect to Predicate
   */
  public static Predicate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Predicate.class);
  }

  /**
   * Convert an instance of Predicate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

