/*
 * AWS Amplify UI Builder
 * <p>The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications. You can then connect these UI components to an application's backend Amazon Web Services resources.</p> <p>You can also use the Amplify Studio visual designer to create UI components and model data for an app. For more information, see <a href=\"https://docs.amplify.aws/console/adminui/intro\">Introduction</a> in the <i>Amplify Docs</i>.</p> <p>The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the <a href=\"https://docs.amplify.aws/\">Amplify Framework</a>. For more information about deploying an Amplify application to Amazon Web Services, see the <a href=\"https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html\">Amplify User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2021-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.FixedPosition;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SectionalElementPosition
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:10:09.976251+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class SectionalElementPosition {
  public static final String SERIALIZED_NAME_FIXED = "fixed";
  @SerializedName(SERIALIZED_NAME_FIXED)
  @javax.annotation.Nullable
  private FixedPosition fixed;

  public static final String SERIALIZED_NAME_RIGHT_OF = "rightOf";
  @SerializedName(SERIALIZED_NAME_RIGHT_OF)
  @javax.annotation.Nullable
  private String rightOf;

  public static final String SERIALIZED_NAME_BELOW = "below";
  @SerializedName(SERIALIZED_NAME_BELOW)
  @javax.annotation.Nullable
  private String below;

  public SectionalElementPosition() {
  }

  public SectionalElementPosition fixed(@javax.annotation.Nullable FixedPosition fixed) {
    this.fixed = fixed;
    return this;
  }

  /**
   * Get fixed
   * @return fixed
   */
  @javax.annotation.Nullable
  public FixedPosition getFixed() {
    return fixed;
  }

  public void setFixed(@javax.annotation.Nullable FixedPosition fixed) {
    this.fixed = fixed;
  }


  public SectionalElementPosition rightOf(@javax.annotation.Nullable String rightOf) {
    this.rightOf = rightOf;
    return this;
  }

  /**
   * Get rightOf
   * @return rightOf
   */
  @javax.annotation.Nullable
  public String getRightOf() {
    return rightOf;
  }

  public void setRightOf(@javax.annotation.Nullable String rightOf) {
    this.rightOf = rightOf;
  }


  public SectionalElementPosition below(@javax.annotation.Nullable String below) {
    this.below = below;
    return this;
  }

  /**
   * Get below
   * @return below
   */
  @javax.annotation.Nullable
  public String getBelow() {
    return below;
  }

  public void setBelow(@javax.annotation.Nullable String below) {
    this.below = below;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectionalElementPosition sectionalElementPosition = (SectionalElementPosition) o;
    return Objects.equals(this.fixed, sectionalElementPosition.fixed) &&
        Objects.equals(this.rightOf, sectionalElementPosition.rightOf) &&
        Objects.equals(this.below, sectionalElementPosition.below);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fixed, rightOf, below);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectionalElementPosition {\n");
    sb.append("    fixed: ").append(toIndentedString(fixed)).append("\n");
    sb.append("    rightOf: ").append(toIndentedString(rightOf)).append("\n");
    sb.append("    below: ").append(toIndentedString(below)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("fixed");
    openapiFields.add("rightOf");
    openapiFields.add("below");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SectionalElementPosition
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SectionalElementPosition.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SectionalElementPosition is not found in the empty JSON string", SectionalElementPosition.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SectionalElementPosition.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SectionalElementPosition` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `fixed`
      if (jsonObj.get("fixed") != null && !jsonObj.get("fixed").isJsonNull()) {
        FixedPosition.validateJsonElement(jsonObj.get("fixed"));
      }
      // validate the optional field `rightOf`
      if (jsonObj.get("rightOf") != null && !jsonObj.get("rightOf").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("rightOf"));
      }
      // validate the optional field `below`
      if (jsonObj.get("below") != null && !jsonObj.get("below").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("below"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SectionalElementPosition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SectionalElementPosition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SectionalElementPosition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SectionalElementPosition.class));

       return (TypeAdapter<T>) new TypeAdapter<SectionalElementPosition>() {
           @Override
           public void write(JsonWriter out, SectionalElementPosition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SectionalElementPosition read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SectionalElementPosition given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SectionalElementPosition
   * @throws IOException if the JSON string is invalid with respect to SectionalElementPosition
   */
  public static SectionalElementPosition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SectionalElementPosition.class);
  }

  /**
   * Convert an instance of SectionalElementPosition to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

